### PR TITLE
Fixed RPM installation source can not be used and some tests

### PR DESCRIPTION
**Pull request by takumakume**
- Fixed MHA RPM storage location was changed.
- Fixed failed to create mysql user for test.

but...test is not pass.
I'm trying it now.

### CODE REVIEW

**Comment by takumakume** [comment]
Original RPM on Google Drive can not use.
- RPM installation source in the repository.
- RPM build are done with the tools to maintain reproducibility.
  - https://github.com/takumakume/mha-rpm

Please check.

**Comment by takumakume** [comment]
RPM on Google Drive can not use.

- RPM installation source in this repository.
  - RPM source is here https://drive.google.com/drive/folders/0B1lu97m8-haWeHdGWXp0YVVUSlk
  - Because it is difficult to get with curl

Please check.

**Review by hfm — APPROVED** [review]
Thanks! 😃

**Comment by hfm** [comment]
Released https://forge.puppet.com/hfm/mha/0.1.0

**Pull request merged**
